### PR TITLE
JMS: Add support for durable subscriptions

### PR DESCRIPTION
**Pull request by liff**
Support durable topic subscriptions by adding `withTopic(name, subscriptionName)` to `JmsConsumerSettings`.

Documentation is missing but I'll certainly add it if the change looks good otherwise.

### CODE REVIEW

**Comment by ennru** [comment]
Looks very useful.
Would be good to split `Topic` into two types instead of the optional subscriber name.
The name `destination` seems a bit overused - can you come up with something else?

**Comment by liff** [comment]
Added new `DurableTopic` type.

Open for suggestions about naming of `destination` :)

**Comment by ennru** [comment]
What about calling it `settingsDestination`,  in `JmsSession` and sub-classes?

**Comment by ennru** [comment]
... and add something to the documentation, please.

**Comment by liff** [comment]
I don't think the test failure is related to this change. The “publish and consume JMS text messages through a queue with client ack” test fails pretty consistently when i run it locally with `testOnly`.

Curiosly the failure disappears if I add a `.log` stage before `.take` [here](https://github.com/akka/alpakka/blob/master/jms/src/test/scala/akka/stream/alpakka/jms/scaladsl/JmsConnectorsSpec.scala#L375).

I usually get this failure, though:

> javax.jms.IllegalStateException, with message: The Session is closed. (JmsConnectorsSpec.scala:385)

It seems like the session sometimes gets closed before all messages have been delivered and/or acked.

**Comment by ennru** [comment]
Check out #867 which proposes a generic way to create JMS destinations. It might be possible to implement your need via it.

**Comment by liff** [comment]
Looks nice but supporting durable subscriptions need a mechanism to also allow custom `MessageConsumer` creation since we need to do `session.createDurableSubscriber(..)` with the provided `Destination`.

**Comment by russellyou** [comment]
Hi, I am creator of #867, I have updated my PR. 

Destination is expanded like
sealed trait Destination {
  val name: String
  def create(name: String): (jms.Session) => jms.Destination
}

This means you can override create method with your session.createDurableSubscriber(..) . 

Let me know your thought please.

**Comment by liff** [comment]
But [`createDurableSubscriber`](https://docs.oracle.com/javaee/7/api/javax/jms/Session.html#createDurableSubscriber-javax.jms.Topic-java.lang.String-) returns a [`MessageConsumer`](https://docs.oracle.com/javaee/7/api/javax/jms/MessageConsumer.html), not a [`Destination`](https://docs.oracle.com/javaee/7/api/javax/jms/Destination.html), right?

So for a durable subscription, the [creation of a consumer](https://github.com/akka/alpakka/blob/master/jms/src/main/scala/akka/stream/alpakka/jms/JmsConnector.scala#L115) also needs to be customized somehow.

**Comment by russellyou** [comment]
Sorry for missing that. You are right. 

The issue is we try to do different thing according to Destination type. If we agree with the proposed approach in #867, we can also put createConsumer function in Destination to avoid complex pattern matching in createConsumer of JmsConnector.scala

**Comment by liff** [comment]
Sounds good to me. To be continued on #867; I'll close this PR.

**Comment by ennru** [comment]
I assume you'd like to propose a new solution to this now that #867 is merged to master.

**Comment by liff** [comment]
Sure, I'll get it going.

**Comment by liff** [comment]
Well, looking at it now, it seems like it'd be actually easier if `Destination` had:

```scala
val consumer: jms.Session => jms.MessageConsumer
val producer: jms.Session => jms.MessageProducer
```

instead of `=> jms.Destination`, which is a rather intermediate thing after all.

If we keep `create: jms.Session => jms.Destination` in `Destination` then the above functions also need `jms.Session` as an additional parameter.

@russellyou what do you think?

**Comment by russellyou** [comment]
If we replace the session => destination with consumer/producer, I guess we have to change lots of existing code. 

This PR looks like only need consumer, not producer , right?  I would rather add val consumer: jms.Session => jms.MessageConsumer for now. 

Just my suggestion:


sealed trait Destination {
 val name: String
 val create: (jms.Session) => jms.Destination
 val consumer: (jms.Session) => jms.MessageConsumer 
}
final case class Topic(override val name: String, create = session =>session.createTopic(name), consumer = session => session.createConsumer(session.createTopic(name)) ) extends Destination

**Comment by russellyou** [comment]
If we replace the session => destination with consumer/producer, I guess we have to change lots of existing code. 

This PR looks like only need consumer, not producer , right?  I would rather add val consumer: jms.Session => jms.MessageConsumer for now. 

Just my suggestion:




`
sealed trait Destination {
 val name: String
 val create: (jms.Session) => jms.Destination
 val consumer: (jms.Session) => jms.MessageConsumer 
}
final case class Topic(override val name: String, create = session =>session.createTopic(name), consumer = session => session.createConsumer(session.createTopic(name)) ) extends Destination 

`

**Comment by ennru** [comment]
Please move this discussion to a new issue.

**Comment by jugalps** [comment]
I am sort of using similar implementation for durable topics, it would be good to have this PR merged. 
@liff - Is there a new issue created for this feature?

**Pull request closed without merging**
