### PR TITLE
Run mqtt-streaming tests in Travis CI

### PR DESCRIPTION
**Pull request by 2m**
We did not add Mqtt Streaming connector to `.travis.yml` in the original PR.

### CODE REVIEW

**Comment by ennru** [comment]
Fixes #1289

**Comment by 2m** [comment]
Failure was https://github.com/akka/alpakka/issues/1269

**Comment by huntc** [comment]
Thanks for fixing this up guys!

**Comment by 2m** [comment]
No problem! Sorry for not noticing that it was missing from the travis config earler. :)

**Pull request merged**
