### PR TITLE
s3 deleteObject

### PR DESCRIPTION
**Pull request by fmsbeekmans**
WIP

Implementation for https://github.com/akka/alpakka/issues/313.

https://github.com/akka/alpakka/pull/563 Looked like it was doing a lot more independent features and might have been abandoned.

I would like some ideas what tests I should add. I tested it manually and it works.
I used a `scala.concurrent.Future` in the JavaDSL, is that the right approach?

TODO
- [ ] Tests
- [ ] Docs

### CODE REVIEW

**Comment by ennru** [comment]
Please have a look at #563 which aims to support delete object as well.

**Comment by francisdb** [comment]
My #563 is not abandoned, just need to find the time to finish it

**Comment by francisdb** [comment]
This should probably be closed now that #563 is merged? Or maybe @fmsbeekmans has some further tweaks he wants applied?

**Comment by johanandren** [comment]
I'll close this since #563 was merged, thanks for the work @fmsbeekmans, please open a new PR if you would want to add some additional functionality to the merged deleteObject.

**Comment by fmsbeekmans** [comment]
No this is fine. Thank you for continuing the PR. I started this one because it was smaller.

**Pull request closed without merging**
