### PR TITLE
SNS: SQS: Bump dependencies

### PR DESCRIPTION
**Pull request by lomigmegard**
Also some quick cleaning to remove warnings.

### CODE REVIEW

**Comment by johanandren** [comment]
There's a couple of more modules using the aws sdk, could you bump all of them to the same version?

**Comment by lomigmegard** [comment]
@johanandren done.
Please test again, failing due to #564.

**Comment by johanandren** [comment]
Was a simple one so I fixed it.

**Comment by johanandren** [comment]
Nop, I think I just forgot to merge, sorry!

**Pull request merged**
