### PR TITLE
extend Elasticsearch WriteMessage with script support

### PR DESCRIPTION
**Pull request by T-Hazzle**
WIP

## References

References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
Hi @thasler / @T-Hazzle 
Sorry if the CLA checker put you off. It looks like you have multiple Github accounts in play. 
It would be great if you get back to this. Please feel free to open a new PR if you have a hard time to sort this out.

**Comment by ennru** [comment]
Hi @T-Hazzle 
The Elasticsearch connector has seen significant changes as the retrying logic got reworked and extracted.
Please rebase your work on the current state and create a new Pull Request.
I'll close this now.

**Pull request closed without merging**
