### PR TITLE
Apache Kudu Connector Flow and Sink

### PR DESCRIPTION
**Pull request by SandishKumarHN**
Apache Kudu Connector Flow and Sink. I have added few examples in docs and I have signed the Lightbend CLA.

### CODE REVIEW

**Comment by SandishKumarHN** [comment]
Hi,

Can someone help me here, I don't see any errors from My Pull Request. I see error from 
[error] (mqtt / Test / test)

need help in resolving this.

**Comment by SandishKumarHN** [comment]
@ennru Can you help me on this??  I don't see any errors from My Pull Request. I see errors for sqs, mqtt but there is no change in any of those modules directly or indirectly.

**Comment by ennru** [comment]
Looks like you merged master into this branch. Please use `git rebase` and `git push -f` instead.

**Comment by SandishKumarHN** [comment]
@ennru does it still needw any changes?

**Comment by 2m** [comment]
Hi @SandishKumarHN!

We need to fix up this branch to only contain the commits related to Apache Kudu before we can go forward and review this.

Please drop the last commit that merged current master to your branch:

```
git reset --hard HEAD^
```

Then fetch the latest master from the origin (that is if the origin points to the `akka/alpakka` in your setup):

```
git fetch origin master:master
```

And then finally rebase your branch from the top of the current master:

```
git rebase master
```

Check out if the results in your branch are what you want with:

```
git log --graph --decorate --pretty=oneline --abbrev-commit --all
```

If the results are what you want, force push the results to the remote branch:

```
git push SandishKumarHN -f
```

**Comment by SandishKumarHN** [comment]
@2m @ennru made changes, there is a JMS test failure.

**Comment by 2m** [comment]
Almost there. I see that your branch now contains two commits, but only the first one is for this connector. You can drop the last commit with `git reset --hard HEAD^` and push the result to this branch.

**Pull request closed without merging**
