### PR TITLE
Make Travis fail build on code format differences

### PR DESCRIPTION
**Pull request by bantonsson**

### CODE REVIEW

**Comment by bantonsson** [comment]
So in its infinite wisdom Travis continues to run the `sbt test` even after the `diff` has *failed* the build. Argh. I'll have another look at why.

**Comment by bantonsson** [comment]
Excellent. A proper failure that stopped the rest of the build. Let's see if it works without the broken indentation.

**Comment by 2m** [comment]
Awesomeness. I think we should have a more contributor friendly message when the diff is not clean. Something like: "Unformatted code found. Please run 'test:compile' and commit the reformatted code."?

**Comment by bantonsson** [comment]
Valid point. I'll change the text.

**Comment by hseeberger** [comment]
LGTM

**Pull request merged**
