### PR TITLE
Mongo: Update driver to 4.4.0

### PR DESCRIPTION
**Pull request by mikela**
Update Mongo driver to v.4.3.0. 
It's the first version compatible with MongoDB 5.0: https://docs.mongodb.com/drivers/java/sync/current/compatibility/#mongodb-compatibility

### CODE REVIEW

**Comment by ennru** [comment]
Do you know if this version is API compatible with the 4.1.1 version?
We would need to make this wait for Alpakka 4.0 if there might be incompatibilities.

**Comment by mikela** [comment]
It is API compatible according to [their release notes](http://mongodb.github.io/mongo-java-driver/4.3/whats-new/).

**Comment by ennru** [comment]
I see version 4.2 changed their Reactive Streams implementation to built on Project Reactor. I'm afraid that might pull in dependencies that could affect users. We need to look closer into that.

**Comment by mikela** [comment]
Hmm right. We can indeed just make this wait for Alpakka 4.0 like you mentioned; if anybody needs to use Mongo 5+ they can just override the dependency (I'm doing that already and it works fine for my use case).

**Comment by mikela** [comment]
Updated from version 4.3.0 to 4.3.2, specific bug fixes [here ](https://jira.mongodb.org/browse/JAVA-4183?jql=project%20%3D%20JAVA%20AND%20fixVersion%20in%20(4.3.1%2C%204.3.2)%20ORDER%20BY%20component%20ASC)

**Comment by mikela** [comment]
Updated from version 4.3.2 to 4.3.3, specific bug fixes [here](https://jira.mongodb.org/browse/JAVA-4309?jql=project%20%3D%20JAVA%20AND%20fixVersion%20%3D%204.3.3%20ORDER%20BY%20component%20ASC)

**Comment by mikela** [comment]
Updated from version 4.3.3 to 4.4.0, which mainly adds support for MongoDB 5.1 and Java 17. All changes [here](https://jira.mongodb.org/browse/JAVA-4235?jql=project%20%3D%20JAVA%20AND%20fixVersion%20%3D%204.4.0%20ORDER%20BY%20component%20ASC)

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Ramping up for Alpakka 4 -- thank you!

**Pull request merged**
