### PR TITLE
MQTT manual acks

### LINKED ISSUE #378: MQTT manual acknowledge
Hi there,

Is there a way to manually acknowledge messages ? I'm using the Java library. Paho supports it by using `void setManualAcks(boolean manualAcks)` of `IMqttAsyncClient` and then acknowledging each message using `void messageArrivedComplete(int messageId, int qos)`.

Or is it so that the message isn't acknowledged before it reaches the sink of the stream ? I don't think that's the case from what I understood of the code. According to Paho's documentation and Alpakka source code, a message is acknowledge as soon as `onMessage(message: MqttMessage): Unit` returns. Here's `onMessage` implementation:
```
private val onMessage = getAsyncCallback[MqttMessage] { message =>
    require(queue.size <= bufferSize)
    if (isAvailable(out)) {
      pushMessage(message)
    } else {
      queue.enqueue(message)
    }
  }
```
To me it looks like this method returns right away but I'm not sure.

Basically I don't want to acknowledge a message before it has reached my sink.

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Add possibility to manually ack messages downstream

Resolves #378

### CODE REVIEW

**Comment by johanandren** [comment]
Travis failure seems like it is related to the changes, please have a look.

**Comment by juanjoDiaz** [comment]
I've been trying to reproduce it but it works on my machine 100% of the time.

The error seems to happen in different tests and be related to the connection closing before it should. That's odd since I haven't modify anything related to the connection closing.

Any hint is welcome 🙂

**Comment by raboof** [comment]
Restarted the jobs, but it's suspicious they all failed...

**Comment by ennru** [comment]
@juanjoDiaz Could you rebase, and incorparate the changes in master.
After that I'll try to understand where the problem is.

**Comment by ennru** [comment]
It fails locally for me as well:
```
[info] mqtt source
[info] - should consume unacknowledged messages from previous sessions using manualAck *** FAILED *** (10 seconds, 138 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 98 times, sleeping 100000000 nanoseconds between each query. (MqttSourceSpec.scala:65)
```

**Comment by juanjoDiaz** [comment]
Our last conclusion was that the connection was closing randomly at some point.
The error on travis looks a bit different than what you get and even is different scala versions in Travis throw different errors. But all of them seems to be the same. The connection closes before it should...

It's strange that I've run the tests at least a hundred times in my machine and haven't been able to replicate. Which setup do you have?

**Comment by ennru** [comment]
I don't do anything more than starting the docker images and running the tests for the mqtt module.

**Comment by ennru** [comment]
Unformatted code found. Please run 'test:compile' and commit the reformatted code.

**Comment by johanandren** [comment]
Now there were a few MQTT test failures

**Comment by juanjoDiaz** [comment]
Yeah, I'm pretty confident at this point that the tests for MQTT are just not very reliable.

There mostly work on my machine but fail on Travis which make me think of timing issues.
Also the tests seems to pass or fail depending on whether you run the source before or after the sink which shouldn't be.
And also I suspect that the order and parallelism with which the test are run affect the results since all of them access the same topics.

**Comment by johanandren** [comment]
One of the tests fails with a 10 s timeout, that sounds like it could be something more to it than just timing sensitivity, maybe there is a bug lurking here?

**Comment by juanjoDiaz** [comment]
I suspect that the timeout is because other test is stealing the message, so the test just hang up forever waiting for the message.

I'll try to look into this.

**Comment by juanjoDiaz** [comment]
There is also something definitely fishy about the stage...
This works:
```
      val elem = source.runWith(Sink.head)
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      elem.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))
```
but this doesn't:
```
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      val elem = source.runWith(Sink.head)
      elem.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))
```
and both should work just the same...

**Comment by johanandren** [comment]
The source only works if the topic has been published to already?

**Comment by juanjoDiaz** [comment]
It's weirder than that.
This works
```
    "support multiple materialization" in {
      val settings = MqttSourceSettings(sourceSettings, Map(topic1 -> MqttQoS.AtLeastOnce))
      val source = MqttSource.atMostOnce(settings, 8)

      val elem = source.runWith(Sink.head)
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      elem.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))

      val elem2 = source.runWith(Sink.head)
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      elem2.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))
    }
```

but this fails
```
    "support multiple materialization" in {
      val settings = MqttSourceSettings(sourceSettings, Map(topic1 -> MqttQoS.AtLeastOnce))
      val source = MqttSource.atMostOnce(settings, 8)

      val elem = source.runWith(Sink.head)
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      elem.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))

      val elem2 = source.runWith(Sink.head)
      Source.single(MqttMessage(topic1, ByteString("ohi"))).runWith(MqttSink(sinkSettings, MqttQoS.atLeastOnce))
      elem2.futureValue shouldBe MqttMessage(topic1, ByteString("ohi"))
    }
```
The weird thing is that it fails on the second materialization not the first one.

Also, based on Travis it seems that we randomly lose messages. I've noticed that I can reproduce it locally adding load to my machine and trying multiple times.

I have no idea of where those messages are going :/

**Comment by johanandren** [comment]
Aren't those two code blocks identical?

**Comment by juanjoDiaz** [comment]
Maybe, you saw it too quickly (I edited it a second after posting).
The second changes the order the source and sink are created.

**Comment by juanjoDiaz** [comment]
Alright! Finally understood the issues.

New Mqtt subscribers only get messages published after they are created for the first time.
So the tests needed to wait until the subscriber is subscribed before start publishing messages.

This is ready now. @johanandren @ennru

**Comment by ennru** [comment]
Is this something the user of this module needs to be aware of? Could it be ensured in the API? Should it be added to the documentation?

**Comment by juanjoDiaz** [comment]
Nothing to do with this module and nothing we can do.
It's just the way MQTT works (which I had misunderstood).

I don't think that it should be documented here since:
- It's just an edge case where you want to initiate publisher and subscriber exactly at the same time one have zero messages lost. Normally it just make sense that you get messages from the time that you create the subscriber for the first time and not before. This doesn't affect a subscriber reconnecting; the state is kept in that case.
- Alpakka doesn't include documentation for how the other systems that there are connectors work

**Comment by ennru** [comment]
Thank you for keeping it up.

**Pull request merged**
