### PR TITLE
Use akka-http 10.2

### PR DESCRIPTION
**Pull request by mrooding**
I've updated alpakka to use akka-http 10.2.4

### CODE REVIEW

**Comment by seglo** [comment]
Looking good. Can you look at the test failure for `google-cloud-pub-sub`? 

https://travis-ci.com/github/akka/alpakka/jobs/497583035#L675

**Comment by seglo** [comment]
I looked into this a bit. The new usage will set additional parameters on the `SSLEngine` that cause failures, but I'm not sure why.

**Comment by mrooding** [comment]
Hey @seglo 

I'll try to find some time to look into it. Couldn't it be related to the fact that Wiremock starts with a self-signed certificate and that we need to skip certificate validation in the tests?

Besides the `google-cloud-pub-sub` failures I also notice *a lot* of stage completion failures. I looked into that a while ago already but couldn't immediately figure out what was going on there.

**Comment by brunogbv** [comment]
Hey all, would you mind sharing current status? I can help if needed

**Comment by mrooding** [comment]
Hi @brunogbv 

I'd like to finish this off but I'll need some input from one of the maintainers. Maybe @seglo or @ennru can give some guidance on this? 

I feel that getting this in in the next minor or major release is very important. We're currently stuck upgrading other akka dependencies until we can switch to akka-http 10.2

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mrooding** [comment]
I was able to fix the test by disabling hostname verification during the test. I'm not 100% satisfies that this is the best approach but it does resolve the issue with the Wiremock server during the test. 

I've resigned the CLA and double-checked that my email address is set up properly but the CLA validator doesn't seem to like it yet.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
Thank you @mrooding for driving this!

IIRC the Alpakka build allows building with both Akka HTTP 10.1 and 10.2 and the user may choose any of those minor versions.
But I agree that it is time to embrace Akka HTTP 10.2 (and Akka gRPC 2.1) fully.

**Requiring Akka HTTP 10.2 will trigger a new major version of Alpakka.**

Your [first commit](https://github.com/mrooding/alpakka/commit/abb929cf31bfcc8ac9cbed260ea472d508116a2a) seems to come from a different GitHub account, the CLA checker doesn't like that.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by mrooding** [comment]
@ennru thanks for the reply. I've rebased and squashed the commits into 1. It seems to recognize me now but the CLA check still fails.

W.r.t. the actual PR, do you have any input on what could be causing the stage completion failures? That seems to be the last hurdle.

**Comment by ennru** [comment]
As it turns out the CLA checker was a bit tired recently. 
I'm afraid I don't have time to look into the errors for the time being.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
@mrooding  With #2777 merged, would you have a chance to rebase this PR?

**Pull request closed without merging**
