### PR TITLE
elasticsearch: ElasticsearchFlowStage now supports custom indexName pr document

### PR DESCRIPTION
**Pull request by mbknor**
This is needed when streaming to an "index-pattern". 

Example:

posting documents to "my-index-2018-01-31" and "my-index-2018-02-01" while search in kibana for "my-index-*"

### CODE REVIEW

**Comment by mbknor** [comment]
Hi @ennru,

I've added some docs about custom index + one more improvement

**Comment by ennru** [comment]
scalaformat diff, please run `test:compile` and push the tiny update.

**Comment by mbknor** [comment]
@ennru scalaformat diff fixed + Added one more improvement to the search :)

**Comment by ennru** [comment]
Thank you for this great improvement!

**Pull request merged**
