### PR TITLE
FTP: Support username/password credentials and key for login

### PR DESCRIPTION
**Pull request by harshalveera**
… with username and password

    * fixes issue #2134

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by harshalveera** [comment]
@Falmarri

**Comment by seglo** [comment]
References #2134

**Comment by seglo** [comment]
@harshalveera Can you add a little more context as to why this change is necessary?  If a password is defined, and key credentials are not, then use the supplied credentials.  Perhaps the problem is that you want to use a username and password for credentials, but are also providing a key with `SftpSettings.withSftpIdentity`, in which case not providing the sftp identity key may resolve it.

**Comment by Falmarri** [comment]
@seglo We have a use case where we need to communicate with a server that requires BOTH private key credentials _and_ a password

**Comment by seglo** [comment]
@Falmarri I see.  It looks like this change breaks existing tests.  Can you take a look and also add a test that takes both credentials and a password?

https://travis-ci.com/akka/alpakka/jobs/284698131

**Comment by seglo** [comment]
There was an issue with the CLA too. Let me know if you have any technical difficulties signing it.

**Comment by Falmarri** [comment]
Yeah my coworker hasn't pushed upstream before. I'll make sure he follows through with both of those things :)

**Comment by harshalveera** [comment]
@seglo @Falmarri : I signed the CLA yesterday.

I am running the unit tests locally and solve the tests issue.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by harshalveera** [comment]
@ennru @Falmarri can you guide me through this LCA issue. 

Screen Shot 2020-02-07 at 2 35 32 PM

Also unit tests passed so can you get the approvals so that we can get this merged in.

**Comment by seglo** [comment]
@harshalveera The problem is that the git identity you used for your commits does not match your github profile. Maybe you could create a new PR with commits from the identity that signed the CLA? /cc @Falmarri

**Pull request closed without merging**
