### PR TITLE
sbt 1.3.7 and new style check

### PR DESCRIPTION
**Pull request by ennru**
## Purpose

Switch to sbt 1.3.6 and do style verification in one step on Travis.

## References

https://github.com/sbt/sbt-java-formatter/pull/53
https://github.com/sbt/sbt-header/pull/170

## Changes

* sbt 1.3.6
* plugin upgrades
* reformat Java sources that weren't reached by the code style check before

### CODE REVIEW

**Comment by ennru** [comment]
Still a few sbt-related problems:
```
Exception in thread "coursier-pool-17-thread-4" Exception in thread "coursier-pool-17-thread-5" java.lang.LinkageError: loader constraint violation: when resolving method "org.bouncycastle.asn1.x509.AlgorithmIdentifier.getAlgorithm()Lorg/bouncycastle/asn1/ASN1ObjectIdentifier;" the class loader (instance of sbt/internal/FlatLoader) of the current class, org/bouncycastle/jcajce/provider/asymmetric/rsa/KeyFactorySpi, and the class loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader) for the method's defining class, org/bouncycastle/asn1/x509/AlgorithmIdentifier, have different Class objects for the type org/bouncycastle/asn1/ASN1ObjectIdentifier used in the signature

	at org.bouncycastle.jcajce.provider.asymmetric.rsa.KeyFactorySpi.generatePublic(Unknown Source)

	at org.bouncycastle.jcajce.provider.asymmetric.util.BaseKeyFactorySpi.engineGeneratePublic(Unknown Source)

	at org.bouncycastle.jcajce.provider.asymmetric.rsa.KeyFactorySpi.engineGeneratePublic(Unknown Source)

	at java.security.KeyFactory.generatePublic(KeyFactory.java:334)

```
https://travis-ci.com/akka/alpakka/jobs/269239132#L608

```
Uncaught error from thread [S3Test-akka.actor.default-dispatcher-4]: loader constraint violation: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader) previously initiated loading for a different type with name "akka/actor/ActorCell", shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[S3Test]

java.lang.LinkageError: loader constraint violation: loader (instance of sbt/internal/ManagedClassLoader$ZombieClassLoader) previously initiated loading for a different type with name "akka/actor/ActorCell"

	at java.lang.ClassLoader.defineClass1(Native Method)

```
https://travis-ci.com/akka/alpakka/jobs/269239141#L709

**Comment by ennru** [comment]
The `LinkageErrors` show for other stuff now?!
Next year's problem...

**Comment by ennru** [comment]
Changed to the new and shiny sbt 1.3.6 and all strange problems went away.

**Comment by seglo** [comment]
Most of the `FtpWithProxyStageTest` tests failed for some reason (https://travis-ci.com/akka/alpakka/jobs/275862450#L1065).  I'll re-run the job.

This is a new timeout failure in simple-codecs: https://travis-ci.com/akka/alpakka/jobs/275862474#L537

Known failures

* https://github.com/akka/alpakka/issues/1801
* https://github.com/akka/alpakka/issues/1649

**Pull request merged**
