### PR TITLE
Lazy source and flow

### PR DESCRIPTION
**Pull request by huntc**
The binding and connection flows were not living up to their contract whereupon they should be re-usable. This PR fixes that.

The PR has been inspired by the findings of Lunfu Zhong (@zhongl) and his PR: https://github.com/akka/alpakka/pull/1552.

### CODE REVIEW

**Comment by 2m** [comment]
The origin PR has been merged. This now needs a rebase.

**Comment by huntc** [comment]
@2m Rebased.

**Comment by zhongl** [comment]
@ennru - I think `p:unix-domain-socket` would be better than `p:mqtt-streaming` for this issue. WDYT?

**Comment by 2m** [comment]
Change LGTM. The formatter needs to be ran so Travis is pleased. Also Scala 2.11 needs to be pleased as well where `flatten` is not available. Instead use `flatMap(identity)`.

**Comment by huntc** [comment]
I'm unsure what you're referring to re. the formatter... I see that https://travis-ci.org/akka/alpakka/jobs/502859776 failed, but not because of formatting.

I've replaced `flatten`. Thanks.

**Comment by 2m** [comment]
Sorry, did not into why the formatter job has failed. Thats right, only Scala 2.11 fix needed here.

**Comment by huntc** [comment]
No probs. 2.11 should now be happy.

**Pull request merged**
