### PR TITLE
Elasticsearch - #1566 - ElasticsearchFlowStage retry logic improvement

### PR DESCRIPTION
**Pull request by nivox**
- failed messages are treated independently to avoid loosing track of previously failed ones
- retry counts are kept per message so to guarantee correct number of retries and intervals
- added test case proving fix correctness

Apart for the added test, this pull request has also been tested on a live system which kept failing with the 1.1.2 release.

# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](./CONTRIBUTING.md)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ ] Have you updated the documentation?
* [x] Have you added tests for any changed functionality?

## Purpose

This pull request corrects ElasticsearchFlowStage retry logic implementation making sure that old failed messages are not lost due to new failures.

## References

References #1566

## Changes

Only the internal implementation of ElasticsearchFlowStage has been changed to keep track of retry counts on a per message basis.

### CODE REVIEW

**Comment by seglo** [comment]
@nivox Thanks for the PR.  I'm going to park this for @ennru to review when he returns (next week).  It seems that the Elasticsearch client may support retry and backoff strategies internally.  We might get this for free without adding our own implementaiton.  IIRC Enno mentioned this at some point, but I'm not sure if it's something we're considering for 2.0.0.

**Comment by ennru** [comment]
I rebased it to get passed the GC Storage error and applied scalafmt.

**Comment by nivox** [comment]
@ennru Thanks for taking the time to look at the PR! 
As you correctly observed this implementation could let to out of order messages. 
More generally this implementation (and as far as I understand the general idea, the implementation based on RetryFlow) could potentially result in out of order writes.

Thinking about it the only way to ensure both message and write order is to limit a single in-flight batch of writes (i.e. bulk operation) and handle all the retries before accepting a new batch. 
This will obviously reduce the throughput but will provide much more robust guarantees that will make the logic suitable for `withContext` scenarios.

I've a rough idea on the implementation which should not require a major rewrite of the current code. If you think this could be of interest I could work on it on another PR.

**Comment by ennru** [comment]
Thank you for this improvement!

My hope is that we can compose the `RetryFlow` from Akka 2.6 with the `ElasticsearchSimpleFlowStage` to achieve retrying without out-of-order responses.
`RetryFlow` allows for only one in-flight message and that reduces throughput as you noticed.
Please give it a try!

**Pull request merged**
