### PR TITLE
Kinesis Firehose support #122

### PR DESCRIPTION
**Pull request by gregbeech**
This direct port of the relevant Kinesis functionality to use the Kinesis Firehose types for #122. I put it in the `kinesis` project rather than creating a new one as this matches the way AWS ship their own libraries. Similarly the `kinesisfirehose` package is used to match AWS.

It's not exactly an elegant solution to have significant portions of the Kinesis code duplicated with just package and type names changed. However, I spent a good while looking at some way to generalise the code but there isn't really that much that can be shared. The graph logic could be extracted out for the flow stage, but it starts to get a little messy and would have an impact on the existing interface, such as requiring exceptions to be generic and adding more methods to `KinesisFlowSettings` with sensible defaults for additional stream types.

My feeling was that the deduplication internally wasn't worth the (mildly) detrimental effect it had on the external interface, and given the connector doesn't currently support either Video or Analytics streams it's possibly too early to try and generalise the implementation (rule of threes and all that).

Thoughts on this approach are welcome. If people are happy with it I'll squash the commits.

### CODE REVIEW

**Comment by ennru** [comment]
Hmm, a shame there is no obvious way a abstract about both Kinesis and Firehose.

**Comment by gregbeech** [comment]
You can extract the `GraphStageLogic` so it's shared between the two, and although it's a little messy it's not too awful. The compromises you need to make are that it would change the interfaces a bit in terms of the exceptions thrown on failure, and the `KinesisFlowSettings` class methods would need a bit of a name change to make them less ambiguous as to which Kinesis variant they're for (as settings for one are totally unsuitable for the other).

Happy to put up an additional commit which shows this so that it's easier to make a call between one and the other. I wasn't convinced it actually made things better overall. But additional opinions on this would be welcome.

**Comment by ennru** [comment]
Does anybody else have an opinion, if we're happy with this logic duplication within the same connector?

**Comment by ennru** [comment]
Thank you for this contribution! Please keep an eye on it to see if we can simplify the Kinesis / Kineses Firehose split.

**Pull request merged**
