### PR TITLE
As time goes by - 2017 headers

### PR DESCRIPTION
**Pull request by ennru**
Upgraded file header config to 2017 and updated file headers.

### CODE REVIEW

**Comment by johanandren** [comment]
Isn't it supposed to be a range when it changes, so if it was 2016 it becomes 2016-2017?

**Comment by 2m** [comment]
Oops. Rebase gone wrong, @ennru ?

**Comment by ennru** [comment]
Must be. It is easier to start over, I reckon.

**Comment by ennru** [comment]
I sent a new PR.

**Pull request closed without merging**
