### PR TITLE
Use Akka HTTP 10.2.9

### PR DESCRIPTION
**Pull request by jrudolph**
On top of #2820 to check if latest snapshot works (in preparation of 10.2.9).

### CODE REVIEW

**Comment by jrudolph** [comment]
@ennru this is a fix against your PR to use 10.2.9 which fixes the SSE issues.

**Comment by jrudolph** [comment]
@ennru this is a fix against your PR to use 10.2.9 which fixes the SSE issues.

**Comment by jrudolph** [comment]
Interesting, the docs problem seems to be that the akka-http apidocs are now missing a lot of classes. Probably not critical but I'll look into what's happened there.

**Comment by jrudolph** [comment]
> Interesting, the docs problem seems to be that the akka-http apidocs are now missing a lot of classes. Probably not critical but I'll look into what's happened there.

Ok, I cannot find those apidocs in older versions as well, so maybe we just shouldn't link to internal classes.

**Comment by jrudolph** [comment]
> Ok, I cannot find those apidocs in older versions as well, so maybe we just shouldn't link to internal classes.

I see, 10.2.7 links were ignored in the link checker. Updated for 10.2.9

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
