### PR TITLE
Ftp 2541 incorrect credentials should complete with a failed future

### PR DESCRIPTION
**Pull request by polentino**
This PR addresses issue https://github.com/akka/alpakka/issues/2541: when wrong credentials are being used to connect to a FTP server, the materialized Future will be completed with a failure containing a `UserAuthException`.

While `UserAuthException` belongs to `sshj` project, thus not really 100% appropriate for `FtpsOperations` and `FtpOperations` (it's only thrown by `SftpOperations`), I believe it looks more consistent from an user perspective rather than throwing for example a `javax.security.auth.login.FailedLoginException` for the Ftp/Ftps cases and a `UserAuthException` in case of `Sftp`.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
Thank you for making this happen in the nested code of Alpakka FTP.

> While UserAuthException belongs to sshj project, thus not really 100% appropriate for FtpsOperations and FtpOperations (it's only thrown by SftpOperations), I believe it looks more consistent from an user perspective rather than throwing for example a javax.security.auth.login.FailedLoginException for the Ftp/Ftps cases and a UserAuthException in case of Sftp.

Wouldn't it be better to define an exception specific to Alpakka in `akka.stream.alpakka.ftp`?

**Comment by polentino** [comment]
> Thank you for making this happen in the nested code of Alpakka FTP.
> 
> > While UserAuthException belongs to sshj project, thus not really 100% appropriate for FtpsOperations and FtpOperations (it's only thrown by SftpOperations), I believe it looks more consistent from an user perspective rather than throwing for example a javax.security.auth.login.FailedLoginException for the Ftp/Ftps cases and a UserAuthException in case of Sftp.
> 
> Wouldn't it be better to define an exception specific to Alpakka in `akka.stream.alpakka.ftp`?

Sure! Any good name suggestion you'd like to propose?

**Comment by ennru** [comment]
`akka.stream.alpakka.ftp.FtpAuthenticationException` ?

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by polentino** [comment]
@ennru do you happen to know why `typesafe-cla-validator` is complaining about the CLA? I've already signed it two times...

**Comment by raboof** [comment]
> @ennru do you happen to know why `typesafe-cla-validator` is complaining about the CLA? I've already signed it two times...

I can confirm the 'polentino' github user is correctly added to our CLA list. The error message suggests that the email address you used for the commits, 'diego.casella@restore.energy', is not associated with your github account (see https://github.com/settings/emails). However github is showing the correct avatar by your commits, suggesting they are actually correctly linked... not sure what's going on there. Can you check your https://github.com/settings/emails just to be sure?

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by polentino** [comment]
> > @ennru do you happen to know why `typesafe-cla-validator` is complaining about the CLA? I've already signed it two times...
> 
> I can confirm the 'polentino' github user is correctly added to our CLA list. The error message suggests that the email address you used for the commits, '[diego.casella@restore.energy](mailto:diego.casella@restore.energy)', is not associated with your github account (see https://github.com/settings/emails). However github is showing the correct avatar by your commits, suggesting they are actually correctly linked... not sure what's going on there. Can you check your https://github.com/settings/emails just to be sure?

My mistake indeed, thanks @raboof ! Rebased properly and now it's green

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you, great to have better feedback.

**Pull request merged**
