### PR TITLE
PassThroughFlow examples in Java

### PR DESCRIPTION
**Pull request by mayankbansal93**
## Purpose
Added the PassThroughFlow examples in Java

## References

References #xxxx

## Changes
Providing support for Java developers by adding the example of PassThroughFlow in Java.

## Background Context
I had to implement the PassThroughFlow in java for my own project. I have successfully created it and making it open to all to use.

### CODE REVIEW

**Comment by 2m** [comment]
This is great! Really appreciated.

However for these code examples to show up in the documentation you will need to add corresponding `@@snip` directives after Scala ones in this documentation file: https://github.com/akka/alpakka/blob/cf7bea1f83879786bd60c3db86425f859d166e6a/docs/src/main/paradox/patterns.md#L65-L67

It would look like this:

```
Java
: @@snip [snip](/doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/PassThroughExamples.java) { #PassThrough }
```

Also you can always run `docs/previewSite` in the sbt shell to see what the output of documentation is.

**Comment by mayankbansal93** [comment]
> This is great! Really appreciated.
> 
> However for these code examples to show up in the documentation you will need to add corresponding `@@snip` directives after Scala ones in this documentation file:
> 
> https://github.com/akka/alpakka/blob/cf7bea1f83879786bd60c3db86425f859d166e6a/docs/src/main/paradox/patterns.md#L65-L67
> 
> It would look like this:
> 
> ```
> Java
> : @@snip [snip](/doc-examples/src/test/java/akka/stream/alpakka/eip/javadsl/PassThroughExamples.java) { #PassThrough }
> ```
> 
> Also you can always run `docs/previewSite` in the sbt shell to see what the output of documentation is.

Okay, I will add the @snip too. I ran the docs/previewSite. Yes, docs are easy to verify. 
I have a doubt, being new to this, should I open a new PR or the same PR would work? 
If so, how to add one more change in the same PR?

**Comment by 2m** [comment]
Usually when PR comes in, there is feedback from community. And it is best to address that feedback by adding commits to the PR. You need to add a new commit to your branch that you created this PR from and then push that branch to the remote, in your case by `git push mayankbansal93`. Then new commits will appear here.

Also a little note: I see you have created this PR from your `master` branch. Better convention would be to do your commits in a different branch (created by `git co -b my-branch-name`) and then create PR from that. This way your `master` branch is kept clean and you will have no problems pulling upstream changes when Alpakka moves forward.

**Comment by mayankbansal93** [comment]
I have added the one more commit regarding the @snip. 
From now onwards I will make sure to create the feature branch for the changes so that the master branch remains clean.

**Pull request merged**
