### PR TITLE
GCS - Owner entityId should be optional

### PR DESCRIPTION
**Pull request by francisdb**
Another field that should be optional
Somehow we ended up with main.scala.akka.stream... packages

References #2163

### CODE REVIEW

**Comment by seglo** [comment]
@francisdb I missed the `main.scala` package issue from your earlier PR.  @ennru fixed the problem in https://github.com/akka/alpakka/pull/2177. Can you rebase on master?

**Comment by francisdb** [comment]
@seglo I did not introduce those, came from #2058

**Comment by francisdb** [comment]
@ennru this is ready for review

**Comment by seglo** [comment]
> @seglo I did not introduce those, came from #2058

My mistake.

**Pull request merged**
