### PR TITLE
MQTT streaming: target Akka 2.6

### PR DESCRIPTION
**Pull request by raboof**
Still failing one test: "MqttSessionSpec: MQTT client connector should receive a QoS 1 publication from a subscribed topic and ack it and then ack it again"

References #2097

### CODE REVIEW

**Comment by ennru** [comment]
Watch out for the Alpakka testkit dependency brought in by `alpakkaProject`.

**Comment by raboof** [comment]
(failure is scaladoc generation, looking into that...)

**Comment by ennru** [comment]
The failure is not new to the branch https://github.com/akka/alpakka/issues/1723

**Comment by ennru** [comment]
Ah, I think it should state Akka 2.6 only, instead.

**Comment by raboof** [comment]
it seems obvious from the dependency table. Do you think we should spell it out further?

DeepinScreenshot_select-area_20200212154646

**Comment by ennru** [comment]
Yes, it is an exception to the rule in Alpakka. 
See https://doc.akka.io/docs/alpakka/2.0/overview.html#versions

**Pull request merged**
