### PR TITLE
Spring-web: support for Spring Boot 2.0

### LINKED ISSUE #1246: Spring Web: Alpakka Spring Web doesn't work with Spring Boot 2.0
Hi there,

I am searching on Spring Akka integrations, and I have found Alpakka. It seems like the current implementation doesn't support Spring Boot 2.0. You can find my example app at: https://github.com/wgx731/dr-spring/blob/master/dr-spring-gateway/src/main/java/com/github/wgx731/gateway/DrSpringGateway.java#L10

The error is Bean **RequestMappingHandlerAdapter** is missing, it seems like Spring Boot 2.0 dropped servelet MVC support by default. 😢I have tried to add **spring-boot-starter-web** or **spring-boot-starter-webmvc** in the dependency, but still no luck. 

Any idea / hint how I can fix this issue?

Thank you very much.

### PR DESCRIPTION
**Pull request by sleipnir**
#1246 Removed unnecessary class injection from spring web module. Updated core core module dependencies and removed direct dependencies from spring-webmvc and spring-webflux.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Velik123,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by sleipnir** [comment]
I already signed the Individual CLA

**Comment by lightbend-cla-validator** [comment]
Hi @Velik123,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by 2m** [comment]
I'll take a look why the CLA validator is still complaining.

**Comment by 2m** [comment]
@sleipnir we can not merge commits that have been authored with a wrong email address. Can you recreate these commits with the correct email address and force-push the new commits to this PR. You can also close this PR and open a new one if that is easier.

**Comment by lightbend-cla-validator** [comment]
Hi @Velik123,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @Velik123,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by sleipnir** [comment]
I will close this pull request and open a new one with the fixes.

**Pull request closed without merging**
