### PR TITLE
Change groupId com.typesafe.akka to com.lightbend.akka

### PR DESCRIPTION
**Pull request by BranislavLazic**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @BranislavLazic,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
Refs #71, LGTM, thanks!

**Comment by ktoso** [comment]
LGTM thanks!

**Comment by ktoso** [comment]
I wonder if we should have one file into which we put all such changes, so people have an easier time upgrading? Given that we don't guarantee stability here such changes will happen, and it would be nice for people to have a CHANGELOG.md I guess for those kinds - kind of like a migration guide more.

WDYT @hseeberger @2m @patriknw @johanandren ?

**Comment by patriknw** [comment]
Yes, sounds good to have a migration guide, but we don't want to track all changes in a several places (issues allready track that).

**Pull request merged**
