### PR TITLE
AMQP: add support for native ConnectionFactory as a configuration option

### PR DESCRIPTION
**Pull request by agboom**
This PR adds a new AmqpConnectionSettings type that accepts a native `ConnectionFactory` from the underlying RabbitMQ client.

The motivation is that I needed to give an SSL truststore with an imported mutual certificate. This required me to inject a `SocketFactory` with that truststore directly into the AMQP `ConnectionFactory`. This isn't supported by the `AmqpConnectionDetails` class. I thought it might be useful in some more complex use cases (like this one) to give the underlying `ConnectionFactory` directly to the Alpakka AMQP graphstage, so you can use the more advanced features of the Java RabbitMQ client.

The new settings type (`AmqpConnectionFactory`) can be constructed with a single `ConnectionFactory`. I maintained support for multiple host/port combinations with an extra `hostAndPorts` parameter. If `hostAndPorts` is empty, the host/port from the `ConnectionFactory` is used.

Please let me know your feedback.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @agboom,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by johanandren** [comment]
How does this relate to #670, overlap/conflict/duplicate?

**Comment by juanjoDiaz** [comment]
Conflict :(

I'll fix it, and add the changes here to #670

**Comment by ennru** [comment]
@juanjoDiaz Thank you for continuing this work. You do not necessarily need to open a new PR when you have to rebase. But I assume you can close this PR than.

**Comment by juanjoDiaz** [comment]
In this case, fixing the rebase conflicts was way more time-consuming than simply creating a new branch. :)

**Pull request merged**
