### PR TITLE
Mongo: driver 4.7.2 (was 4.4.0), adds full support for MongoDB 6.0

### PR DESCRIPTION
**Pull request by mikela**
More info https://www.mongodb.com/docs/drivers/java/sync/current/whats-new/

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @mikela,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by mikela** [comment]
Signed

**Comment by ennru** [comment]
It looks like some warnings do not apply anymore:
```
[error] /home/runner/work/alpakka/alpakka/mongodb/src/test/scala/docs/scaladsl/MongoSinkSpec.scala:42:101: @nowarn annotation does not suppress any warnings
[error]     fromRegistries(fromProviders(classOf[Number], classOf[DomainObject]), DEFAULT_CODEC_REGISTRY): @nowarn(
[error]                                                                                                     ^
[error] /home/runner/work/alpakka/alpakka/mongodb/src/test/scala/docs/scaladsl/MongoSourceSpec.scala:54:52: @nowarn annotation does not suppress any warnings
[error]     fromRegistries(fromProviders(classOf[Number]: @nowarn("msg=match may not be exhaustive")), DEFAULT_CODEC_REGISTRY)
[error]                                                    ^
[error] two errors found
```

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you!

**Pull request merged**
