### PR TITLE
JMS: fix connection leak issue

### PR DESCRIPTION
**Pull request by russellyou**
fix jms connection leak issue since 0.16

### CODE REVIEW

**Comment by russellyou** [comment]
Hi, I may need some help here. 

Got error when building:
[error] Unformatted code found. Please run 'test:compile' and commit the reformatted code.

When I run sbt test:compile locally. 

I got out of memory error

[success] Total time: 5 s, completed 31/01/2018 9:12:06 AM
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:200)
[error] 	at sbt.Execute.next$1(Execute.scala:99)
[error] 	at sbt.Execute.processAll(Execute.scala:102)
[error] 	at sbt.Execute.runKeep(Execute.scala:79)
[error] 	at sbt.EvaluateTask$.liftedTree1$1(EvaluateTask.scala:383)
[error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:382)
[error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:401)
[error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:96)
[error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:327)
[error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:94)
[error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:107)
[error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:64)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:121)
[error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:216)
[error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:310)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:121)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:105)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:227)
[error] 	at sbt.State$$anon$1.process(State.scala:233)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:105)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:105)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:98)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:76)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:70)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:52)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:37)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:29)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:104)
[error] 	at sbt.xMain.run(Main.scala:71)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] Caused by: java.lang.OutOfMemoryError: Metaspace
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[error] 	at com.lucidchart.sbt.scalafmt.BridgeClassLoader.findClass(BridgeClassLoader.scala:11)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at scala.reflect.ManifestFactory$.<init>(Manifest.scala:115)
[error] 	at scala.reflect.ManifestFactory$.<clinit>(Manifest.scala)
[error] 	at scala.reflect.ClassManifestFactory$.<init>(ClassManifestDeprecatedApis.scala:152)
[error] 	at scala.reflect.ClassManifestFactory$.<clinit>(ClassManifestDeprecatedApis.scala)
[error] 	at scala.reflect.package$.<init>(package.scala:36)
[error] 	at scala.reflect.package$.<clinit>(package.scala)
[error] 	at scala.Predef$.<init>(Predef.scala:116)
[error] 	at scala.Predef$.<clinit>(Predef.scala)
[error] 	at org.scalafmt.Versions$.<init>(Versions.scala:24)
[error] 	at org.scalafmt.Versions$.<clinit>(Versions.scala)
[error] 	at org.scalafmt.config.ScalafmtConfig$.apply$default$1(ScalafmtConfig.scala:2)
[error] 	at org.scalafmt.config.Settings$class.$init$(Settings.scala:20)
[error] 	at org.scalafmt.config.ScalafmtConfig$.<init>(ScalafmtConfig.scala:49)
[error] 	at org.scalafmt.config.ScalafmtConfig$.<clinit>(ScalafmtConfig.scala)
[error] 	at org.scalafmt.config.Config$.fromHocon(Config.scala:42)
[error] 	at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:11)
[error] 	at com.lucidchart.scalafmt.impl.ScalafmtFactory.fromConfig(ScalafmtFactory.scala:9)
[error] 	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$.$anonfun$scalafmtCoreSettings$26(ScalafmtCorePlugin.scala:154)
[error] 	at com.lucidchart.sbt.scalafmt.ScalafmtCorePlugin$autoImport$$$Lambda$2422/1981900848.apply(Unknown Source)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] Use 'last' for the full log.



I have a 16G memory mac book.  
question, 

1 Is there any easy way to fix the OOM issue?
2 Won't scalafmt do the magic of formatting? Is test:compile mandatory?


Thanks!

**Comment by ennru** [comment]
Try to run it for the jms module only: `jms/test:compile`

**Comment by raboof** [comment]
1. Interesting, I don't get a `java.lang.OutOfMemoryError: Metaspace`, weird. Compiling only the jms subproject like @ennru suggested should work, or `export SBT_OPTS='-XX:MaxMetaspaceSize=512m'`
2. Yes, perhaps we should suggest `test:scalafmt` instead of `test:compile` here!

**Comment by ennru** [comment]
Fixes #733

**Comment by russellyou** [comment]
I fixed the format issue. Now the build failed because of either of below 2 tests


ensure no message loss when stopping a stream 
ensure no message loss when aborting a stream

BTW  2.11 passed.

*** FAILED *** (2 minutes, 2 seconds)


[info]   A timeout occurred waiting for a future to complete. Queried 1998 times, sleeping 60 milliseconds between each query. (JmsAckConnectorsSpec.scala:250)
...


I have no issue running these tests locally. Looks like the failure is intermittent. Could it caused by slow environment?

**Comment by ennru** [comment]
Yes, Travis is way slower than a local environment. The 2.11 build worked OK after I re-triggered it.
We might need to extend the patience even more.

**Comment by russellyou** [comment]
2.12 still fail. 

Will someone extend the patience? Or I can do it if you have a rough guess of Travis speed.

**Comment by ennru** [comment]
The patience is 2 mins already. Something else must be flaky. I triggered the Travis job once more.

**Comment by ennru** [comment]
Thank you for fixing this. Great to have you engaged in Alpakka!

**Pull request merged**
