### PR TITLE
Bump paradox and use the new dependency directive

### PR DESCRIPTION
**Pull request by jonas**

### CODE REVIEW

**Comment by johanandren** [comment]
I'm not 100% sure about this, since it's hosted over at developer.lightbend.com rather than on akka.io it should probably follow the styling over there?

**Comment by jonas** [comment]
Does the Paradox update and refactoring still make sense?

**Comment by johanandren** [comment]
I think the other changes make sense! Sorry, should have been a bit more clear that the concern was just about the akka-theme.

**Comment by jonas** [comment]
@johanandren Thanks for the clarification. Fixed and rebased.

**Comment by johanandren** [comment]
Thanks @jonas !

**Pull request merged**
