### PR TITLE
Support for Dynamodb Streams

### PR DESCRIPTION
**Pull request by joost-de-vries**
This PR provides an initial implementation for Dynamodb Streams. See issue #447 
I thought we can release this in 'alpha' status to get feedback. What do you think?

This should probably be labeled `p:dynamodb`

Next steps:
- add test that will use multiple shards
- add test that triggers resharding

### CODE REVIEW

**Comment by dylan-raithel-lookout** [comment]
What happens in this code when a shard splits or merges? Are you relying on the Supervisor to handle restart and then re-describing the streams?

**Comment by joost-de-vries** [comment]
@dylan-raithel-lookout the documentation really doesn't specify how resharding affects the api. It mentions that its a concern and advises to use the kinesis adapter. 
So I couldn't implement that just from the documentation. The next step would be, I think, to do some load tests with really good logging. And analyse the behaviour of the api. 
Do you have any ideas?

**Comment by dayyan** [comment]
Here's what I see in [documentation for the Kinesis API].(http://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-sdk.html#kinesis-using-sdk-java-get-data-reshard)

>If `getRecordsResult.getNextShardIterator` returns `null`, it indicates the following: a shard split or merge has occurred that involved this shard, this shard is now in a `CLOSED` state, and you have read all available data records from this shard.
>
>In this scenario, you should re-enumerate the shards in the stream to pick up the new shards that were created by the split or merge.

**Comment by joost-de-vries** [comment]
@dayyan good idea. That documentation definitely gives some direction in how to implement this. I remember some docs saying that the semantics are not 1-to-1 the same though.

Wrt the dynamodb adapter: are you suggesting to use that as an intermediary? I guess it's an option. There's [a Kinesis adapter of course ](https://developer.lightbend.com/docs/alpakka/current/kinesis.html) but that doesn't handle iterating over shards or handle resharding out of the box.

Unfortunately I'm rather busy currently. So I can't say I'll work on this very soon. If you want to take a crack at it: by all means.

Implementing those semantics is perhaps not the hardest thing: I'm wondering how to trigger resharding in a unittest in a predictable manner.

**Comment by ennru** [comment]
This PR hasn't been touched for a very long time.
Please re-open or create a new to continue this work.

**Comment by Normal** [comment]
need this feature

**Pull request closed without merging**
