### PR TITLE
HDFS: New path per file

### PR DESCRIPTION
**Pull request by bondarenko**
References https://github.com/akka/alpakka/issues/2577

Adding by the PR a **FilePathGenerator** option of creating a new path for each file depending on rotation count and timestamp supplied by hdfs messages.
An assumption is that each hdfs message in addition to source and passThrough contains a timestamp. This timestamp in succession is used to create a file path. The specific file path format as before is defined in a function supplied to **FilePathGenerator**.
An example of specific path template we can use for path creation with this option on:
`s"/$year/$month/$day/$hour-$rotationCount"`.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by seglo** [comment]
Hi @bondarenko. You'll need to sign the Lightbend CLA with the github identity you're using for your commits. Another option is to rewrite the commits with the identity you signed with, or create a new PR.

**Comment by bondarenko** [comment]
Hi @seglo. I've recreated this pull request [here](https://github.com/akka/alpakka/pull/2607).

**Pull request closed without merging**
