### PR TITLE
AWS SDK 2.10.34

### PR DESCRIPTION
**Pull request by sullis**
## References

References #xxxx

### CODE REVIEW

**Comment by ennru** [comment]
https://travis-ci.com/akka/alpakka/jobs/259855779#L779 in #2006

**Comment by ennru** [comment]
Known failures were 
#1802 
#2006

But this is new. It showed even after a re-trigger, so we need to understand if it could be related to the version change.
```
SqsSourceSpec:
SqsSource
- should enable throttling on emptyReceives and disable throttling when a new message arrives *** FAILED *** (62 milliseconds)
  java.lang.AssertionError: Expected OnNext(_), yet no element signaled during 10 milliseconds
  at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:347)
  at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:802)
  at akka.stream.alpakka.sqs.scaladsl.SqsSourceSpec.$anonfun$new$7(SqsSourceSpec.scala:136)
  at akka.stream.alpakka.sqs.scaladsl.SqsSourceSpec.$anonfun$new$7$adapted(SqsSourceSpec.scala:136)
  at scala.collection.immutable.Range.foreach(Range.scala:190)
  at akka.stream.alpakka.sqs.scaladsl.SqsSourceSpec.$anonfun$new$6(SqsSourceSpec.scala:136)
```
https://travis-ci.com/akka/alpakka/jobs/259855785#L988

**Comment by ennru** [comment]
The same new failure does still show. Can you go up to 2.10.33, please.

**Comment by sullis** [comment]
I just bumped this to SDK 2.10.34

**Comment by ennru** [comment]
Failures were #1954 #1801 #1549

**Pull request merged**
