### PR TITLE
[elasticsearch] Prepend the index name to the url in _bulk operations when necessary

### PR DESCRIPTION
**Pull request by Tommmster**
## Purpose
Enables the use of the Elasticsearch Sink in non-default environments where url-based access control is performed.

## References

References #1843 

## Changes

* Adding two fields to `ElasticsearchFlowStage [T,C]`: The actual endpoint to which the `_bulk` request will be performed and a method that includes (or not ) the index name on each document. The Stage contains all necessary information at construct-time.
 
## Background Context

Current implementation of the Elastic search Sink will fail (requests rejected) if the cluster configuration does not hold the default setting for the `rest.action.multi.allow_explicit_index` property, which is common when url-based access control is performed (multi-tenancy)

These changes enabled the elasticsearch sink to work in these conditions, while preserving the current behaviour by default.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by Tommmster** [comment]
Signed CLA

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by 2m** [comment]
Hi @Tommmster. Thank you for the PR. Implementation looks good. It is nice to see that the effort we put into un-case-classing settings classes pays off here, where it is possible to add a new settings parameter in a binary compatible way.

Binary Compatibility check in Travis failed, because you need to add an issue filter for the changed constructor. That is fine, as the constructor is private and is not exposed to the user facing API. You can add such filter by creating a `elasticsearch/src/main/mima-filters/1.1.0.backwards.excludes` file with the following content:

```
ProblemFilters.exclude[DirectMissingMethodProblem]("akka.stream.alpakka.elasticsearch.ElasticsearchWriteSettings.this")
```

Now the CLA checker failed to verify because it can not map the commit author to your GitHub profile. Please squash all of the commits in the PR to a single one and make sure to use the same email as you have set in your GitHub profile.

**Comment by ennru** [comment]
@Tommmster 	It would be great if you can come back to this PR and fix the obstacles.

**Comment by ennru** [comment]
Superseded by #2326

**Pull request closed without merging**
