### PR TITLE
S3: Add some backoff delay to multipart upload retries for tests

### PR DESCRIPTION
**Pull request by bpiper**
…to try and address intermittent failures (#2209).

No guarantees this will address the failures, but I can't replicate them locally, so will have to rely on Travis.

### CODE REVIEW

**Comment by bpiper** [comment]
Just going to trigger Travis builds until either the test failure recurs or I'm satisfied that the issue may be resolved.  Please don't merge until I've squashed/rebased to remove the superfluous commits.

**Comment by bpiper** [comment]
Ok, I've run something like 24 Travis builds and the failure hasn't recurred (two of the builds did fail, but for unrelated reasons), so I'm confident that in the worst case this change hasn't made things any worse, and has quite possibly addressed the intermittent failures, so it's RTBM from my perspective.

**Comment by bpiper** [comment]
@ennru would you mind giving this a quick review when you have time (or flick it to someone else)? Thanks.

**Comment by ennru** [comment]
Thank you for following up on this!

**Pull request merged**
