### PR TITLE
Jms scala3

### PR DESCRIPTION
**Pull request by Arikuti**
Compile Alpakka jms scala3

References #xxxx

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Arikuti,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by ennru** [comment]
Hi @Arikuti,

Did you succeed locally? Scala 3 has a few complaints on things in the JMS module which you would need to solve. Switch to Scala 3 in sbt with `++3.2.2`.

**Comment by Arikuti** [comment]
raised another one

**Comment by Arikuti** [comment]
compiled locally and fixed issues with scala 3 and raised new PR :
JMS: enable Scala 3, bump Scala versions #3007. - please review it 
And alos please let me know how to run workflow immediately after raising PR 
Thanks

**Pull request closed without merging**
