### PR TITLE
Document AQMP versions support

### PR DESCRIPTION
**Pull request by juanjoDiaz**
Documents the issue mentioned in #933

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
I wanted to add a list of AMQP 0.9.1 brokers and 1.0 brokers (since there are more than RabbitMQ and ActiveMQ) but I haven't been able to find a comprehensive list...

I've added at least some names in there :)

**Comment by giftig** [comment]
Might also be worth adding a hint about alternatives to using AMQP with these queues - for example AMQ and Solace both support half a dozen different protocols, including REST interfaces, though whether alpakka can help with any of those protocols I don't know as I'm just trying it out for the first time now. (of course, akka-http is perfectly viable to hit a REST interface though)

Thanks for the quick turnaround on the issue, by the way.

**Comment by juanjoDiaz** [comment]
I'm not sure if it's in the scope of Alpakka's documentation to go deeper on the different MQ brokers and the protocols they support.

We provide a connector to AMQP 0.9.1 and we make a particular note that 1.0 is not supported to avoid unclarity. But I wouldn't go any deeper than that.

Btw, as a side note, Alpakka provides an MQTT connector among others so it's definitely worth looking into them.

**Comment by giftig** [comment]
Fair enough; I thought it might be useful to offer a hint of where else to look if the right AMQP version isn't supported, but given there may be a growing list of AMQP 1.0 applications there, each with their own alternative protocols, that may indeed be too much info.

**Pull request merged**
