### PR TITLE
HUAWEI Push Kit

### PR DESCRIPTION
**Pull request by atyutin90**
There was added integration with HUAWEI Push Kit for possibility to send messages to apps on huawei users' devices in real time.

### CODE REVIEW

**Comment by ihostage** [comment]
@ennru @seglo For extending context about the reasons of this PR:
https://stackoverflow.com/a/64101008/11124202
> **As new Huawei phones are banned from using GMS, firebase cannot be used on new Huawei phones.** Huawei already provided such notification service, called HMS Push Kit, in order to make push notification available on the devices which don’t have GMS, like mate30, mate30 pro, P40 and any other Huawei new devices. If you want your app to run on these phones, integrate Huawei Push Kit.

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you for your efforts. We'll most likely release Alpakka 3.0.4 next week.

**Comment by ihostage** [comment]
Thank you a lot, Enno! 🎉

**Pull request merged**
