### PR TITLE
Make JmsSink materialize to Future[Done]

### PR DESCRIPTION
**Pull request by nilsga**
Sometimes it's useful to know when the stream has completed. Materializing `JmsSink` to a `Future` makes this easier.

### CODE REVIEW

**Comment by ennru** [comment]
Very good API improvement!

**Comment by nilsga** [comment]
Thanks for merging! I did forget to update the documentation though, so will submit another PR.

**Comment by ennru** [comment]
The code in the docs are snippets from the test cases. It should be alright.

**Comment by viktorklang** [comment]
@ennru Since this is bincompat breaking, will it require a 0.16.0 or will it ship in next minor? (Trying to plan since I need it (the feature))

**Comment by johanandren** [comment]
@viktorklang We don't have any bincomp promise for Alpakka (yet)

**Comment by ennru** [comment]
@viktorklang And you can expect to find Alpakka 0.16 at Maven Central on Friday - Release is planned for Thursday.

**Comment by viktorklang** [comment]
@ennru Perfect, I can test/validate that it works on my code as soon as the bits have synced on Thursday. Let me know.

**Comment by viktorklang** [comment]
@johanandren :)

**Pull request merged**
