### PR TITLE
Added information for dependencies to use for HBase connector

### PR DESCRIPTION
**Pull request by davideicardi**
For newbie like me can be useful to quickly understand what library to use. Or maybe we can provide a common Alpakka page that list all the latest version of the libraries?

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @davideicardi,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by davideicardi** [comment]
Just signed the CLA

**Comment by ennru** [comment]
Great that you found out and want to improve the docs!
Please add it this way 
```
## Artifacts

@@dependency [sbt,Maven,Gradle] {
  group=com.lightbend.akka
  artifact=akka-stream-alpakka-hbase_$scalaBinaryVersion$
  version=$version$
}
```
to keep it up to date for future releases.

**Comment by davideicardi** [comment]
@ennru Changed pull request following your suggestion. Thanks!

**Comment by ennru** [comment]
Thank you for adding this. I wasn't aware it was missing. Please continue to propose improvements!

**Pull request merged**
