### PR TITLE
fix #357 correct signing for listing buckets with virtual-hosted style access

### LINKED ISSUE #357: AWS S3 Invalid signature calculation
There is still a case where signatures are wrong

when listing using non-path style access in `us-east-1`

```
S3Exception, with message: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

continuation of #342

notifying @2m

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by francisdb** [comment]
I give up trying to get the CI build to work, see #360

**Comment by raboof** [comment]
Refs #357

**Comment by francisdb** [comment]
@2m please also merge this one before 0.10 as it fixes a regression in one of the previous pull requests

**Comment by francisdb** [comment]
thanks

**Pull request merged**
