### PR TITLE
AWS SQS towards 1.0 - major API changes

### LINKED ISSUE #1091: AWS SQS: become Alpakka 1.0 ready
- [x] Move internal code to `impl` package
- [x] Mark internal code `@InternalApi` and `private[connector]`
- [x] Move documentation example code to packages `docs.javadsl` and `docs.scaladsl`
- [x] Make settings to be non-case classes

### PR DESCRIPTION
**Pull request by ennru**
Fixes #1091.

The diff is quite huge as a lot of code has moved around.

I changed the API a bit to remove the use of tuples as flow data type, mainly for the Java side of things.
So it might be good if @aserrallerios can have a look regarding is ideas in #829.

### CODE REVIEW

**Comment by ennru** [comment]
Thank you @aserrallerios, very good input.
I've taken your ideas into account and made even larger changes to the API to get it much more consistent.

**Comment by ennru** [comment]
I even wonder if `SqsAckFlow` is the best name, wouldn't `SqsActionFlow` describe better what it offers?

**Comment by aserrallerios** [comment]
My 2 cents:

But `Publish` can also be an action :)

And after giving it a thought, I think that we should keep them separated, as the input of both streams is different:

* Ack (IN: a consumed message from SQS)
   * ignore
   * delete
   * republish
* Publish (IN: a message body)

Which term can include the three `Ack` types but not `Publish`? For lack of a better term I'd stick to `Ack`.

**Comment by ennru** [comment]
Yes, separated they need to be. I just contemplated if `Ack` is misleading as more sounds data receiving thing where you can acknowledge received messages. But it is about updating the queue instead.

**Comment by 2m** [comment]
Regarding `SqsAckFlow` I also think that having ignore delete and republish all under `ack` can be a bit confusing. Normally `ack` is meant as a positive acknowledgement of a message.

What about `SqsConfirmFlow`? Or `SqsAfterPublishFlow`?

**Comment by aserrallerios** [comment]
And what about dropping the `Ignore` action? If someone wants to ignore messages he doesn't even need a custom Flow/Sink.

I'm not sold on `Confirm`, usually the confirm term is reserved as security double-check step before executing an action.

**Comment by 2m** [comment]
Good point about dropping `Ignore`. If we have only delete and republish left, then calling it `SqsAckFlow` is not that bad.

We could also use `Ack` and `Nak` (negative acknowledgement) in the connector for delete and republish actions.

**Comment by 2m** [comment]
Needs a rebase.

**Pull request merged**
