### PR TITLE
Update to Akka v2.6.15

### PR DESCRIPTION
**Pull request by armanbilge**
References #2683

### CODE REVIEW

**Comment by ennru** [comment]
Thank you for keeping things up here!
We try to avoid changing the versions of Akka dependencies in patch releases, I suggest we park this until we are ramping up for Alpakka 3.1.0 or 4.0.0

**Comment by rtyley** [comment]
I'd particularly like to see an upgrade to Akka v2.6.**16**, as it has https://github.com/akka/akka/pull/30375 - a fix for the `scala-java8-compat` issue with sbt v1.5's eviction-errors that's been spilling into various places (like https://github.com/playframework/playframework/pull/10966 & https://github.com/scanamo/scanamo/pull/1176).

**Comment by ennru** [comment]
> I'd particularly like to see an upgrade to Akka v2.6.16

As Akka is binary-compatible, you're free to use a later Akka version than what Alpakka ships with. 
See https://doc.akka.io/docs/akka/current/project/downstream-upgrade-strategy.html

**Comment by rtyley** [comment]
> As Akka is binary-compatible, you're free to use a later Akka version than what Alpakka ships with.

That's certainly true, however, even though I can definitely specify Akka v2.6.16 as a dependency in my own projects, if those projects are also _even indirectly_ dependent on an alpakka artifact, sbt 1.5 still regards the varying versions of `scala-java8-compat` in the dependency tree as fatally-incompatible, and won't compile unless those errors are disabled for the entire project with `evictionErrorLevel := Level.Info`.

**Comment by ennru** [comment]
Right, that is very annoying. Akka had to introduce a Scala-version-dependent version for it:

https://github.com/akka/akka/blob/8e5493fb1af29db8f5c98b8897f2dd557aa11456/project/Dependencies.scala#L71-L78

**Comment by ennru** [comment]
@rtyley Does specifying the dependency explicitly in your build solve this?
```sbt
"org.scala-lang.modules" %% "scala-java8-compat" % "1.0.0"
```

**Comment by ennru** [comment]
@rtyley I was told, you'll have to tell sbt to rely on the version you picked:

`ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-java8-compat" % VersionScheme.Always`

**Comment by rtyley** [comment]
> @rtyley I was told, you'll have to tell sbt to rely on the version you picked:
> 
> `ThisBuild / libraryDependencySchemes += "org.scala-lang.modules" %% "scala-java8-compat" % VersionScheme.Always`

Thanks @ennru, you're completely right - many thanks for pointing that out!

**Comment by ennru** [comment]
@armanbilge We're ramping up for Alpakka 4.0 would you like to bring Alpakka to the latest Akka version?
BTW: We intend to drop Scala 2.12 for Alpakka 4.0 #2777

**Comment by armanbilge** [comment]
@ennru thanks for the ping, unfortunately I'm spread too think to be able to work on this. It would be great if whoever takes that on can cherry-pick my changes from here, but they were nothing critical, just removing workarounds for now-fixed bugs.

**Comment by ennru** [comment]
Ok, I made the upgrade to Akka 2.6.18 part of #2777

**Pull request closed without merging**
