### PR TITLE
Use akka-http 10.2.9

### PR DESCRIPTION
**Pull request by ennru**
Rebased @mrooding's PR #2650 to only use the current Akka HTTP version.
Will need a few more changes to avoid deprecated APIs.

Supersedes #2650

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
The tests for HTTP-based connectors show a number of failures to shut down in time. Needs some more investigation.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
> `docs.scaladsl.EventSourceSpec` in `sse` seemed like a new failure, re-running to verify

They are a new failure with Akka HTTP 10.2.8 vs 10.2.7. 
* "EventSource should communicate correctly with an instable HTTP server" could be an effect of the better shutdown
* "EventSource should read gzipped replies" is the other new failure

**Comment by ennru** [comment]
https://github.com/akka/akka-http/pull/4020 in Akka HTTP SSE seems to cause the new failures

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
I created #2832 for the SSE problem and downgraded to Akka HTTP 10.2.7 in this PR so we can bring the other changes in.

**Comment by raboof** [comment]
seems some javadoc links are broken
```
`[https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java.base/java/lang/Comparable.html`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java.base/java/lang/Comparable.html%60) should be
`https://docs.oracle.com/pls/rdman/handle404?X_ORCL_404path=%2fen%2fjava%2fjavase%2f11%2fdocs%2fapi%2fjava.base%2fjava.base%2fjava%2flang%2fComparable.html`
```

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by ennru** [comment]
> seems some javadoc links are broken - why is java.base in there twice?

Great that you saw this. I removed the workaround for https://github.com/ThoughtWorksInc/sbt-api-mappings/issues/58

The Pravega site seems to be unreachable at the moment, though.

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Review by raboof — APPROVED** [review]
I took the liberty of rebasing to attach the original commit to @mrooding's account properly so he gets the proper PR credits after merging and the cla checker is happy.

Nice one! :tada:

**Comment by ennru** [comment]
Thank you @mrooding for getting this work started!

**Pull request merged**
