### PR TITLE
Added configuration support for requests over HTTP #247

### PR DESCRIPTION
**Pull request by thereisnospoon**

### CODE REVIEW

**Comment by johanandren** [comment]
Refs #247

**Comment by johanandren** [comment]
Since it is only ever `http` or `https`, wouldn't a boolean setting make more sense?

**Comment by svezfaz** [comment]
+1 on the boolean param. Maybe we could have the setting as
```
   proxy {
      ...
      secure = true
    }
```

**Comment by thereisnospoon** [comment]
Thanks for review. I've made changes according to your comments.
I've accidentally committed some housekeeping comments (I've worked from two stations). If there is such a need I can repair that and squash them.

**Pull request merged**
