### PR TITLE
Bump `akka-http` version to `10.1.1` and `akka-http-circe` to `1.20.1` to resolve http unbind failure

### PR DESCRIPTION
**Pull request by randomcoder**
This should resolve the `IllegalStateException: IO Listener actor terminated unexpectedly for remote endpoint`
error which was fixed in the `10.1.x` `akka-http` series

See: https://github.com/akka/akka-http/issues/1837

Re: #913 #915

### CODE REVIEW

**Comment by ennru** [comment]
Compilation error in Ironmq connector.
```
[info] Compiling 14 Scala sources to /home/travis/build/akka/alpakka/ironmq/target/scala-2.11/classes ...
[error] /home/travis/build/akka/alpakka/ironmq/src/main/scala/akka/stream/alpakka/ironmq/IronMqClient.scala:76:77: value getOrElse is not a member of io.circe.Decoder.Result[io.circe.Json]
[error]       def extractName(json: Json) = json.hcursor.downField("name").as[Json].getOrElse(Json.Null)
[error]                                                                             ^
[error] /home/travis/build/akka/alpakka/ironmq/src/main/scala/akka/stream/alpakka/ironmq/IronMqClient.scala:225:71: value map is not a member of io.circe.Decoder.Result[akka.stream.alpakka.ironmq.Reservation.Id]
[error]           reservationId <- json.hcursor.downField("reservation_id").as[Reservation.Id]
```

**Comment by ennru** [comment]
Ah, you saw it already.

**Comment by ennru** [comment]
It would be great if you can identify this issue. Akka-http will release a new version quite soon, but I'm not sure if anything connected to this will be solved.

**Comment by randomcoder** [comment]
Having a good look around, I am thinking that the issue might be in the `start()` method of the `SQSRestServerBuilder` which finishes by creating an `SQSRestServer` with
```scala
SQSRestServer(appStartFuture, () => {
  appStartFuture.flatMap { sb =>
    stopActorSystem()
    sb.unbind()
  }
})
```

See: https://github.com/adamw/elasticmq/blob/master/rest/rest-sqs/src/main/scala/org/elasticmq/rest/sqs/SQSRestServerBuilder.scala#L183

As the underlying issue is a race condition where the server is being asked to `Terminate` before it has received an `Unbind` request this looks a likely candidate.

I can raise a PR for elasticmq to swap the lines over, but that will take a little time to test and validate.

@ennru What are your thoughts?

**Comment by randomcoder** [comment]
The elasiticmq PR is: https://github.com/adamw/elasticmq/pull/141

**Comment by randomcoder** [comment]
Just waiting for the 0.13.11 elasticmq release now.

**Comment by gregbeech** [comment]
Should make sure this goes to 10.1.3 as [10.1.2 has a serious memory leak](https://akka.io/blog/news/2018/06/15/akka-http-10.1.3-released)

**Comment by ennru** [comment]
We'd want to cross-test with Akka Http 10.0.x and 10.1.x before merging this. We'll use sbt 1.2's new support for it as soon as it is final.

**Comment by ennru** [comment]
Thank you for this contribution!
We decided to upgrade to Akka Http 10.1.x now and add cross-building with 10.0.x shortly.

**Pull request merged**
