### PR TITLE
fix #316 corrects S3 url path handling for keys with spaces

### LINKED ISSUE #316: AWS S3 url encoding bug
We have a bucket object with a a space in it's key

```scala
val key = "my object"
S3Client.download(bucket, key)
```

fails with the following error

```
akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input ' ', expected '/', 'EOI', '#', '?' or pchar (line 1, column 34): /waylay.plugins/app.templates/CO2 OK template
                                 ^
    at akka.http.scaladsl.model.IllegalUriException$.apply(ErrorInfo.scala:40)
    at akka.http.scaladsl.model.Uri$.fail(Uri.scala:752)
    at akka.http.impl.model.parser.UriParser.fail(UriParser.scala:80)
    at akka.http.impl.model.parser.UriParser.parseUriReference(UriParser.scala:45)
    at akka.http.scaladsl.model.Uri$.apply(Uri.scala:209)
    at akka.http.scaladsl.model.Uri$.apply(Uri.scala:181)
    at akka.stream.alpakka.s3.impl.HttpRequests$.requestUri(HttpRequests.scala:111)
    at akka.stream.alpakka.s3.impl.HttpRequests$.akka$stream$alpakka$s3$impl$HttpRequests$$s3Request(HttpRequests.scala:87)
    at akka.stream.alpakka.s3.impl.HttpRequests$.getDownloadRequest(HttpRequests.scala:39)
    at akka.stream.alpakka.s3.impl.S3Stream.request(S3Stream.scala:93)
    at akka.stream.alpakka.s3.impl.S3Stream.download(S3Stream.scala:63)
    at akka.stream.alpakka.s3.scaladsl.S3Client.download(S3Client.scala:50)
```

the case with a key of for example "my dir/my object.json" should also work (no encoding of the `/`'s)

when manually replacing `" "` with `"%20"` I get 403 Forbidden which indicates the signing is also broken with these kinds of url's

(the official client happily accepts keys with spaces)

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by francisdb** [comment]
Build failed on unrelated test

```
[error] Failed: Total 13, Failed 1, Errors 0, Passed 12
[error] Failed tests:
[error] 	akka.stream.alpakka.mqtt.scaladsl.MqttSourceSpec
```

**Comment by francisdb** [comment]
Hmm, now there suddenly are compile errors? 😯

**Comment by francisdb** [comment]
🙌

**Comment by vlovgr** [comment]
Thanks for this! 👍 I'm still seeing signing errors, like the following, when downloading using a key containing spaces.
```
akka.stream.alpakka.s3.S3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$entityForSuccess$1(S3Stream.scala:256)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by francisdb** [comment]
Do you have a reproducer so I can add tests? What settings/region/key name?

**Comment by vlovgr** [comment]
Looking at the documentation for the S3 API (http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html), the recommendation for the `UriEncode` method is to use a custom `UriEncode` method which they provide.

Currently, `/abc/DEF/2017/06/15/1234 (1).TXT` gets encoded to:
- `/abc/DEF/2017/06/15/1234%20(1).TXT`

but with their custom implementation the encoding is:

- `/abc/DEF/2017/06/15/1234%20%281%29.TXT`.

Here's a quick Scala rewrite of their `UriEncode` function which I used for the example:
```
def toHexUtf8(ch: Char): String = "%" + Integer.toHexString(ch.toInt)

  def uriEncode(input: CharSequence, encodeSlash: Boolean = true): String = {
    val result = new StringBuilder
    var i = 0
    while ({ i < input.length }) {
      val ch = input.charAt(i)
      if ((ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '_' || ch == '-' || ch == '~' || ch == '.')
        result.append(ch)
      else if (ch == '/')
        result.append(
          if (encodeSlash) "%2F"
          else ch
        )
      else result.append(toHexUtf8(ch))

      { i += 1; i - 1 }
    }
    result.toString
  }
```

**Comment by francisdb** [comment]
@vlovgr thanks for testing and looking into this.

> Encode the forward slash character, '/', everywhere except in the object key name. For example, if the object key name is photos/Jan/sample.jpg, the forward slash in the key name is not encoded.

Not sure I fully get this, but testing to see what works. Will post updated pr soon

**Comment by francisdb** [comment]
@vlovgr please have an other go at this

(I will be offline until Monday morning)

by the way a key of `/abc/DEF/2017/06/15/1234 (1).TXT` will give you an empty string folder in the root of the bucket, you should not be using leading slashes.
I wonder what the official java aws s3 client drops the trailing slash in that case

**Comment by vlovgr** [comment]
The leading slashes are coming directly from listing the contents of a bucket.
```
s3Client.listBucket("bucket", Some("key"))
```

I can confirm that this fixes the signing problems. 👍

**Comment by francisdb** [comment]
For my part this is ready for merge

**Pull request merged**
