### PR TITLE
sbt 1.4

### PR DESCRIPTION
**Pull request by ennru**

### CODE REVIEW

**Comment by ennru** [comment]
The log colouring has disappeared even though we have

https://github.com/akka/alpakka/blob/master/.jvmopts-travis#L4

Lint warnings for `autoApiMappings`, `projectInforVersion` and `whitesourceIgnore`.

**Comment by ennru** [comment]
Interesting, with sbt 1.4.1 all output goes into a single line.
https://travis-ci.com/github/akka/alpakka/jobs/402352309#L393

**Comment by ennru** [comment]
See https://github.com/sbt/sbt/issues/5995

**Comment by ennru** [comment]
https://github.com/sbt/sbt/issues/5995 is fixed now, chances are sbt 1.4.2 will be colourful and multi-line.

**Review by raboof — APPROVED** [review]

**Pull request merged**
