### PR TITLE
Upgrade to scalafmt 0.6.6

### PR DESCRIPTION
**Pull request by hseeberger**
The original work for this PR has been contributed by @stephennancekivell in #216.

Please notice that the binPack.callSite setting is deprecated and broken and hence had to be removed.

### CODE REVIEW

**Comment by hseeberger** [comment]
Any objections against merging?

**Comment by ktoso** [comment]
Let's give it a few days, we commented on a lot of PRs this week so awaiting to merge a few, then we can merge this one to avoid making conflicts with the incoming PRs.

Let's merge after the next minor release, which would be some time during the middle of next week.

**Comment by hseeberger** [comment]
@ktoso are we ready to merge?

**Comment by ktoso** [comment]
Ok on my end, double checking with @patriknw @johanandren @2m @jrudolph ?

**Comment by johanandren** [comment]
Go!

**Comment by 2m** [comment]
Alright!

**Comment by hseeberger** [comment]
Yay!

**Pull request merged**
