### PR TITLE
Kinesis: remove cleanup function, separate batching and writing

### PR DESCRIPTION
**Pull request by hagerf**
…esisFlow

References #2814

### CODE REVIEW

**Comment by hagerf** [comment]
As an example usage, this is how we currently use it in our code base:
```
  def createRestartKinesisWritingFlowWContext[Ctx](
      kinesisStreamConfig: KinesisStreamConfig,
      cleanupContexts: Ctx => Unit
  )(implicit system: ActorSystem, akkaUtilsConfig: AkkaUtilsConfig): KinesisWriteFlowWithContext[Ctx] = {
    val kinesisWriteSettings: KinesisFlowSettings = getKinesisWriteSettings(kinesisStreamConfig)

    val restartableKinesisSink: Flow[Iterable[(PutRecordsRequestEntry, Ctx)], (PutRecordsResultEntry, Ctx), NotUsed] =
      RestartFlow.withBackoff(akkaUtilsConfig.kinesisDefaultRestartSettings) { () =>
        akkaUtilsConfig.messengerLogger.logRestartComponent(s"kinesis sink `${kinesisStreamConfig.stream}`")
        implicit val amazonKinesisAsyncClient: KinesisAsyncClient = buildKinesisClient(kinesisStreamConfig)
        batchWritingFlow[PutRecordsResultEntry, Ctx](
          kinesisStreamConfig.stream,
          batch => {
            case Success(putRecordsResponse) => Success(handlePutRecordsSuccess(batch)(putRecordsResponse))
            case Failure(throwable) =>
              batch.foreach(t => cleanupContexts(t._2))
              Failure(FailurePublishingRecords(throwable))
          },
          kinesisWriteSettings
        )
      }
    batchingFlow(kinesisWriteSettings).via(restartableKinesisSink)
  }

```

**Comment by ennru** [comment]
Ok, this reverts parts of #2815 and the user with needs for special handling will want to re-use the existing `handlePutRecordsSuccess`, right?

**Comment by hagerf** [comment]
> Ok, this reverts parts of #2815 and the user with needs for special handling will want to re-use the existing `handlePutRecordsSuccess`, right?

Yes, it does revert previous changes. And the user with needs for special batching or (more commonly) special handling of the messages can use either their own Success/Failure handling or just add a failure handling if the `handlePutRecordsSuccess` is enough for Success. In my own case I'm using my own handlers returning an `(Either[KinesisFailedBatch, PutRecordsResultEntry], Ctx)`.

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
