### PR TITLE
CI checks in GitHub actions

### PR DESCRIPTION
**Pull request by ennru**
Moves some checks from Travis to GitHub actions
Refs https://github.com/lagom/lagom/pull/3331

### CODE REVIEW

**Comment by ennru** [comment]
The FTP integration tests don't work and require further investigation.
See even https://github.com/akka/alpakka/issues/1810

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
I relaunched this build to verify an issue we are facing in a Lagom build (https://github.com/lagom/lagom/pull/3336). And it's also failing here. 

The `coursier/setup-action@v1` is failing to download sbtn.

**Comment by ennru** [comment]
This setup-action error is induced by https://github.com/coursier/setup-action/issues/171 and https://github.com/coursier/setup-action/issues/163

**Pull request merged**
