### PR TITLE
AMQP: support naming connections

### PR DESCRIPTION
**Pull request by pliljenberg**
Make it possible to set a name on the connection to rabbitmq. While resolving issues this is quite useful :)

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @pliljenberg,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by pliljenberg** [comment]
CLA signed

**Comment by pliljenberg** [comment]
Hmm. None that I see at the moment at least

**Comment by ennru** [comment]
Hej Peter, thank you for your contribution!

**Comment by pliljenberg** [comment]
Do we have a date set for v0.19? 😀

**Comment by ennru** [comment]
We'll try to shape things up and release v0.19 in the second week of May.
Hopefully, we'll see nightly builds before that.

**Pull request merged**
