### PR TITLE
Update test expectations for Splitter

### LINKED ISSUE #2378: SplitterSpec: Splitter must backpressure only if all outputs are pulled
https://travis-ci.com/github/akka/alpakka/jobs/372494816
```
info] Splitter
[info] - must input splitting (10 milliseconds)
[info] - must backpressure only if all outputs are pulled - if only requested from true *** FAILED *** (37 milliseconds)
[info]   Some(2) did not equal None (SplitterSpec.scala:63)\
[info]   Analysis:
[info]   Some(value: 2 -> )
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.matchers.MatchersHelper$.indicateFailure(MatchersHelper.scala:344)
[info]   at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.shouldEqual(Matchers.scala:6860)
[info]   at akka.stream.alpakka.googlecloud.bigquery.impl.util.SplitterSpec.$anonfun$new$3(SplitterSpec.scala:63)
```

### PR DESCRIPTION
**Pull request by raboof**
Since Akka 2.6.2 (https://github.com/akka/akka/pull/28467), 'filter' has
a 1-element buffer, to be able to 'throw away' filtered-out messages even
when there is no downstream demand.

This changes the behavior in a way that makes the SplitterSpec fail.

I updated the tests to make looser assumptions about the amount of buffering,
and only look at what happens when one of the filter slots is filled.
Unfortunately/surprisingly the test now doesn't appear to pass on Akka 2.5,
I'm proposing to put it on 'ignore' until we start requiring Akka 2.6.

/cc @tg44

fixes #2378

### CODE REVIEW

**Comment by tg44** [comment]
I think this is not the way. We should rewrite the splitter as a custom stage instead.

This connector has a cycle in it. Which means it will deadlock if we mess up the pulls. This is the reason we wrote these tests for the first time. We need an implementation to satisfy the tests, and not in the other way (write the tests to satisfy an implementation).

**Comment by seglo** [comment]
@tg44 Makes sense. I read your other comments in the issue too.

**Comment by tg44** [comment]
I will write the stage later today if you want to, I don't think it's a huge thing :D (But now I will leave for some (probably 4) hours, so I pass it if its ASAP.)

**Comment by raboof** [comment]
> We need an implementation to satisfy the tests, and not in the other way (write the tests to satisfy an implementation).

I agree wholeheartedly!

> We should rewrite the splitter as a custom stage instead

I agree it might make sense to go for a custom stage indeed. If the backpressure behaviour requirements are so subtle, I'm not sure if composing the solution from a Splitter and a Delay stage is still helpful - perhaps it would be better to have one custom Delay stage without the need for splitting? Anyway, just a thought, I'll leave this up to you.

> I will write the stage later today if you want to

That would be great!

(marking this PR as draft so we don't accidentally merge it)

**Pull request closed without merging**
