### PR TITLE
AmqpSink: fix Scaladoc text

### PR DESCRIPTION
**Pull request by MichelEdkrantz**
Should not include replyTo in apply documentation

Please check

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @MichelEdkrantz,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by MichelEdkrantz** [comment]
CLA signed

**Comment by ennru** [comment]
Scalafmt dislikes it. Please run `sbt scalafmtAll` and push again.

**Comment by ennru** [comment]
Thank you for engaging with Alpakka!

We're close to merging #1921 which updates these comments, so I'll close this PR.

**Pull request closed without merging**
