### PR TITLE
Upgrade scalafmt to 6.1. This requires contributers to manually run s…

### PR DESCRIPTION
**Pull request by stephennancekivell**
…calafmt, and travis to check it.

Hi, let me start by saying I love scalafmt, and I liked how it was setup with scalafmt-on-compile. Sadly thats no longer a supported feature of scalafmt and alpakka is lagging behind. There are some formatting features I'd like to propose, but arent supported in 4.10.

Anyway how about this. Upgrade to 6.1 and ask contributors to manually run scalafmt in sbt. Travis can check it for us too.

This is almost as good as scalafmt-on-compile, which isnt perfect, It freaks out my IntelliJ. :)

### CODE REVIEW

**Comment by hseeberger** [comment]
You can easily enable scalafmt automation with this file (`project/AutomateScalafmt.scala`): https://gist.github.com/olafurpg/e045ef9d8a4273bae3e2ccf610636d66

**Comment by stephennancekivell** [comment]
Hi @hseeberger, I did see that but thought it might not be reliable. But it looks like you've had some experience with it! If you say its good we may as well go with that.

Thanks for your help.

**Comment by hseeberger** [comment]
I have been using it in various projects and so far I'm very confident that it's "reliable".

**Comment by stephennancekivell** [comment]
Thanks hseeberger, I've added a new PR with that approach.

**Pull request closed without merging**
