### PR TITLE
sync google modules jwt-core version

### LINKED ISSUE #1762: Google Cloud Pub/Sub: build for Scala 2.13
It requires an upgrade of "com.pauldijou" %% "jwt-core" from 2.1 to 3.0.1 which needs to be investigated for compatibility rules.

https://github.com/pauldijou/jwt-scala/releases

### LINKED ISSUE #1763: Google Cloud FCM: Build for Scala 2.13
It requires an upgrade of "com.pauldijou" %% "jwt-core" from 2.1 to 3.0.1 which needs to be investigated for compatibility rules.

https://github.com/pauldijou/jwt-scala/releases

### LINKED ISSUE #1811: 1.1.0 incompatibility between google-pub-sub and google-storage
jwt-core dependency on google-pub-sub diverges from google-storage

### Versions used 

Alpakka `1.1.0`

We use both modules and have the following exceptions
###

```
java.lang.NoSuchMethodError: pdi.jwt.JwtTime$.nowSeconds()J
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.now(GoogleTokenApi.scala:26)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleTokenApi.getAccessToken(GoogleTokenApi.scala:41)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.getNewToken(GoogleSession.scala:18)
    at akka.stream.alpakka.googlecloud.pubsub.impl.GoogleSession.$anonfun$getToken$1(GoogleSession.scala:29)
```

jwt-core 3.x has some breaking changes where implicit Clock was added to time functions

All alpakka modules should depend on jwt-core 3.x (`JwtCoreVersion` in build.sbt), currently GooglePubSub and GoogleFcm still depend on 2.x

related?
https://github.com/akka/alpakka/blob/07443516b9fc7f3c0fdd5b582b6422b7a5cea3bd/build.sbt#L161

### PR DESCRIPTION
**Pull request by francisdb**
fixes #1811 and enable scala 2.13 cross build for all google modules
fixes #1762
fixes #1763

As jwt-core 2 and 3 are not compatible this is a breaking change

to continue the cleanup see #773

### CODE REVIEW

**Comment by francisdb** [comment]
Build failures are unrelated?

@enru What are your thoughts on #773 ? Has this been done before, do you see a need to remove duplication between the three google modules?

**Comment by ennru** [comment]
Thank you. I believe independence of the connectors is valuable as well. So I'd leave it as it is for another round.

**Comment by ennru** [comment]
master is ready to merge Alpakka 2.0 PRs. Can you rebase this and remove the exclusion in https://github.com/akka/alpakka/blob/master/build.sbt#L77 now that all modules use the same JWT version, please?

**Comment by francisdb** [comment]
@ennru applied, rebased and squashed

**Comment by ennru** [comment]
Failure was https://github.com/akka/alpakka/issues/1549

**Comment by ennru** [comment]
Thank you!

**Pull request merged**
