### PR TITLE
Kinesis: code layout

### PR DESCRIPTION
**Pull request by YikSanChan**
Group override def together for better readability

### CODE REVIEW

**Comment by YikSanChan** [comment]
@aserrallerios Do you mind reviewing this? Thanks!

**Comment by YikSanChan** [comment]
@ennru Got Albert's approval, do you mind taking a look?

**Comment by YikSanChan** [comment]
@ennru Resolved

**Comment by ennru** [comment]
Thank you for all your suggestions to improve the code in tiny steps. Very appreciated.

**Pull request merged**
