### PR TITLE
Handle failed Future when invoking ES endpoint in Source

### PR DESCRIPTION
**Pull request by brunoballekens**
application of PR#2702 to ElasticsearchSourceStage

References #2702 which fixes the issue in the ElasticsearchSimpleFlowStage

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @brunoballekens,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by brunoballekens** [comment]
I did now sign the CLA

**Review by ennru — APPROVED** [review]
LGTM.

**Comment by ennru** [comment]
Thank you!

**Comment by brunoballekens** [comment]
Glad to help !

**Pull request merged**
