### PR TITLE
Update to sbt 1.1.0 and latest plugin versions

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by takezoe** [comment]
Build fails by format checking. It seems that line breaking behavior of scalafmt has been changed somewhere between 1.0.0 and 1.3.0. Should I push reformatted code?

**Comment by ennru** [comment]
Let's wait until close to the next release so it disturbs ongoing PRs as little as possible.

**Comment by ennru** [comment]
@takezoe Now would be good to do these upgrades and to reformat the sources.
Pick sbt 1.1.1 while at it.

**Comment by ennru** [comment]
Ping @takezoe 
I'd like to cut a 0.17 release tomorrow, would be good to get the reformatting done before.

**Comment by ennru** [comment]
Ok, I'll merge this and put another PR to fix the tiny re-formatting changes on top of it.

**Comment by takezoe** [comment]
@ennru Sorry for my delayed response and thanks for #791!

**Pull request merged**
