### PR TITLE
Remove javac options that confuse javadoc

### PR DESCRIPTION
**Pull request by raboof**
The javadoc tool returned an error (and failed the build) for me because of the
-Xlint:unchecked option which is passed to javadoc but not
recognized there.

### CODE REVIEW

**Comment by 2m** [comment]
Which command failed for you? AFAICS unidoc does not generate Javadoc in Alpakka.

**Comment by raboof** [comment]
`sbt package` is fine, but `sbt publishLocal` gives the error for me

**Comment by 2m** [comment]
This is interesting. Since the spring-web alpakka module has only Java code, the `spring-web/compile:doc` task starts javadoc (in contrast this task for all other projects starts scaladoc).

The proper fix would be to scope the javacOptions to compile task, so it is not picked up by the doc task:

```
diff --git a/project/Common.scala b/project/Common.scala
index bcb767c..8e74141 100644
--- a/project/Common.scala
+++ b/project/Common.scala
@@ -40,7 +40,7 @@ object Common extends AutoPlugin {
       "-Ywarn-dead-code",
       "-Xfuture"
     ),
-    javacOptions ++= Seq(
+    javacOptions in compile ++= Seq(
       "-Xlint:unchecked"
     ),
     autoAPIMappings := true,
```

**Comment by 2m** [comment]
Nice. Validation issue was #527

**Pull request merged**
