### PR TITLE
Fix broken recovery of EventSource (sse)

### PR DESCRIPTION
**Pull request by hseeberger**
Unfortunately there's no easy way for an automated test, because testing requires killing an SSE server forcibly. docker-it might be a solution, but this plugin hasn't been used for Alpakka so far.

Anyway, the existing (not exhaustive) tests are still green, hence I consider it a valid refactoring. And of course it really fixes the bug ;-)

### CODE REVIEW

**Comment by hseeberger** [comment]
See #206.

**Comment by hseeberger** [comment]
Gosh! Looks like some CSV test fails. This is not fair :-(

**Comment by patriknw** [comment]
@ennru can you talk a look at failing csv tests when you have a moment?

**Comment by ennru** [comment]
What test is failing? Can't find a trace of test failures.

**Comment by hseeberger** [comment]
Was a flaky one. Rerunning Travis did the trick.

**Comment by hseeberger** [comment]
@ennru, you have to go to Travis and look up old build runs.

**Comment by hseeberger** [comment]
Any other maintainers open for a review? This is a pretty important fix (without the connector is more or less completely useless) and I'd like to get it in ASAP.

**Pull request merged**
