### PR TITLE
JMS: enable Scala 3, bump Scala versions

### PR DESCRIPTION
**Pull request by Arikuti**
- fix code to support scala 3 in jms

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
At least one commit author (arikuti@arikutis-mbp.home) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by Arikuti** [comment]
sign the CLA. - done

**Comment by lightbend-cla-validator** [comment]
At least one commit author (arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one commit author (arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home, arikuti@arikutis-mbp.home) is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Pull request closed without merging**
